# Generated by Django 5.1.3 on 2024-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_otp',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
