# Generated by Django 5.1.3 on 2024-11-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comment_like_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
